/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demoproject;

import java.util.HashMap;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import com.syncfusion.docio.*;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.regex.Pattern;
import com.syncfusion.docio.*;
import com.syncfusion.javahelper.system.StringSupport;
import com.syncfusion.javahelper.system.text.regularExpressions.MatchSupport;
import com.syncfusion.javahelper.system.globalization.CultureInfoSupport;

public class App {
    public String getGreeting() {
        return "Hello!";
    }

    public static void main(String[] args) throws FileNotFoundException, Exception {
        System.out.println(new App().getGreeting());
		System.out.println(CultureInfoSupport.getCurrentCulture());
		//Open an existing document from the stream using the constructor of the WordDocument class.
		FileInputStream fileStreamPath = new FileInputStream("unable-to-upload.docx");
		WordDocument document = new WordDocument(fileStreamPath, FormatType.Automatic);
		document.save("Resaved.docx");
		document.close();
		System.out.println("Document generated.");
    }
}
